### ISSUE TITLE
remove ibombshell

### ISSUE THREAD

**Issue by Moltivie** [Telefonica/ibombshell#4]
ibombshell opens by itself!

**Comment by rusopro** [comment]
i have the same problem

**Comment by Josue87** [comment]
Check the modules you have launched. If you have used any of UAC bypass, check the windows registry (regedit), for any iBombShell entry (the path you can get from the module code, variable path).  For example: https://github.com/ElevenPaths/ibombshell/blob/Dev/data/functions/bypass/uac/invoke-environmentinjection
